export const COURSES = [
    "BCA DDU",
    "BCA AKTU",
    "BBA DDU",
    "BBA AKTU",
    "MBA",
    "MCA",
    "BPHARM",
    "DPHARM",
    "Polytechnic EE",
    "Polytechnic MEP",
    "Polytechnic CE",
    "Polytechnic PDGT",
    "Polytechnic CSE",
    "BTECH CE",
    "BTECH ECE",
    "BTECH AIML",
    "BTECH ME",
    "BTECH CSE",
    "BTECH DS",
    "MTECH CSE",
    "MPHARM Pharmaceutical Chemistry",
    "MPHARM Pharmacology",
    "MPHARM Pharmaceutics",
];
